In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_csv_data = pd.read_csv('Absenteeism_data.csv')

In [3]:
raw_csv_data

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...
695,17,10,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,28,6,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,18,10,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,25,23,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,15,28,31/05/2018,291,31,40,237.656,25,1,1,1,2

In [83]:
df = raw_csv_data.copy()
df

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...
695,17,10,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,28,6,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,18,10,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,25,23,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,15,28,31/05/2018,291,31,40,237.656,25,1,1,1,2

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         700 non-null    int64
 1   Reason for Absence         700 non-null    int64
 2   Date                       700 non-null    object
 3   Transportation Expense     700 non-null    int64
 4   Distance to Work           700 non-null    int64
 5   Age                        700 non-null    int64
 6   Daily Work Load Average    700 non-null    float64
 7   Body Mass Index            700 non-null    int64
 8   Education                  700 non-null    int64
 9   Children                   700 non-null    int64
 10  Pets                       700 non-null    int64
 11  Absenteeism Time in Hours  700 non-null    int64
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB

##Dropping Columns

In [85]:
df.drop(['ID'],axis=1) #temporary change

,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...
695,10,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,6,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,10,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,23,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,28,31/05/2018,291,31,40,237.656,25,1,1,1,2

In [86]:
df = df.drop(['ID'],axis=1) #permanent change

In [87]:
df

,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...
695,10,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,6,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,10,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,23,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,28,31/05/2018,291,31,40,237.656,25,1,1,1,2

In [88]:
df_no_age = df.drop(['Age'],axis=1)

In [89]:
df_no_age

,Reason for Absence,Date,Transportation Expense,Distance to Work,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,26,07/07/2015,289,36,239.554,30,1,2,1,4
1,0,14/07/2015,118,13,239.554,31,1,1,0,0
2,23,15/07/2015,179,51,239.554,31,1,0,0,2
3,7,16/07/2015,279,5,239.554,24,1,2,0,4
4,23,23/07/2015,289,36,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...
695,10,23/05/2018,179,22,237.656,22,2,2,0,8
696,6,23/05/2018,225,26,237.656,24,1,1,2,3
697,10,24/05/2018,330,16,237.656,25,2,0,0,8
698,23,24/05/2018,235,16,237.656,25,3,0,0,2
699,28,31/05/2018,291,31,237.656,25,1,1,1,2

##Analysing Single Column

In [90]:
df['Reason for Absence']

0      26
1       0
2      23
3       7
4      23
       ..
695    10
696     6
697    10
698    23
699    28
Name: Reason for Absence, Length: 700, dtype: int64

In [91]:
df['Reason for Absence'].min()

0

In [92]:
df['Reason for Absence'].max()

28

In [93]:
pd.unique(df['Reason for Absence'])

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16])

In [94]:
df['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16])

In [95]:
len(df['Reason for Absence'].unique())

28

In [96]:
sorted(df['Reason for Absence'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28]

##Dummy Variables

In [97]:
reasons_columns = pd.get_dummies(df['Reason for Absence'])

In [98]:
reasons_columns

,0,1,2,3,4,5,6,7,8,9,...,18,19,21,22,23,24,25,26,27,28
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
696,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
697,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
698,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
699,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [99]:
reasons_columns['check']= reasons_columns.sum(axis = 1)
reasons_columns

,0,1,2,3,4,5,6,7,8,9,...,19,21,22,23,24,25,26,27,28,check
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,1
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,1
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,1
3,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,1
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,1
696,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,1
697,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,1
698,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,1
699,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,1

In [100]:
reasons_columns['check'].sum(axis = 0)

700

In [101]:
reasons_columns['check'].unique()

array([1])

In [102]:
reasons_columns = reasons_columns.drop(['check'],axis = 1)
reasons_columns

,0,1,2,3,4,5,6,7,8,9,...,18,19,21,22,23,24,25,26,27,28
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
696,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
697,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
698,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
699,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [103]:
#drop 0 col from reasons_columns for multicolinearity

reasons_columns = pd.get_dummies(df['Reason for Absence'], drop_first=True)
reasons_columns

,1,2,3,4,5,6,7,8,9,10,...,18,19,21,22,23,24,25,26,27,28
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
696,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
697,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
698,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
699,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [104]:
age_dummies = pd.get_dummies(df['Age'])

In [105]:
age_dummies

,27,28,29,30,31,32,33,34,36,37,...,39,40,41,43,46,47,48,49,50,58
0,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
696,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
697,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
698,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
699,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

##Group Reason for Absence

In [106]:
df.columns.values

array(['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours'], dtype=object)

In [107]:
reasons_columns.columns.values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 21, 22, 23, 24, 25, 26, 27, 28])

In [108]:
#when inserting reasons_columns into df it has same values as Reason for Absence this leads to multicoleanrity
# drop Reason for Absence because they have same values as reasons_columns

df = df.drop(['Reason for Absence'], axis=1)
df

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,23/07/2015,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...
695,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,31/05/2018,291,31,40,237.656,25,1,1,1,2

In [109]:
# adding reasons_columns directly will add unnecessary no of columns so we group the variables based on the reason type

In [110]:
#retrive 1st 14 columns
reasons_columns.loc[:,1:14]

,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,False,False,False,False,False,False,False,False,False,True,False,False,False,False
696,False,False,False,False,False,True,False,False,False,False,False,False,False,False
697,False,False,False,False,False,False,False,False,False,True,False,False,False,False
698,False,False,False,False,False,False,False,False,False,False,False,False,False,False
699,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [111]:
reasons_columns.loc[:,1:14].max(axis=1)

0      False
1      False
2      False
3       True
4      False
       ...
695     True
696     True
697     True
698    False
699    False
Length: 700, dtype: bool

In [112]:
#max is uded to check if we have value 1 in that column and return it
reason_type1 = reasons_columns.loc[:,1:14].max(axis=1)
reason_type2 = reasons_columns.loc[:,15:17].max(axis=1)
reason_type3 = reasons_columns.loc[:,18:22].max(axis=1)
reason_type4 = reasons_columns.loc[:,22:].max(axis=1)

In [113]:
reason_type3

0      False
1      False
2      False
3      False
4      False
       ...
695    False
696    False
697    False
698    False
699    False
Length: 700, dtype: bool

##Concatenate Column Values

In [114]:
df

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,23/07/2015,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...
695,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,31/05/2018,291,31,40,237.656,25,1,1,1,2

In [115]:
# adding grouped reasons_columns values to df

df = pd.concat([df,reason_type1, reason_type2,reason_type3, reason_type4],axis=1)

In [116]:
df

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,0,1,2,3
0,07/07/2015,289,36,33,239.554,30,1,2,1,4,False,False,False,True
1,14/07/2015,118,13,50,239.554,31,1,1,0,0,False,False,False,False
2,15/07/2015,179,51,38,239.554,31,1,0,0,2,False,False,False,True
3,16/07/2015,279,5,39,239.554,24,1,2,0,4,True,False,False,False
4,23/07/2015,289,36,33,239.554,30,1,2,1,2,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,23/05/2018,179,22,40,237.656,22,2,2,0,8,True,False,False,False
696,23/05/2018,225,26,28,237.656,24,1,1,2,3,True,False,False,False
697,24/05/2018,330,16,28,237.656,25,2,0,0,8,True,False,False,False
698,24/05/2018,235,16,32,237.656,25,3,0,0,2,False,False,False,True
699,31/05/2018,291,31,40,237.656,25,1,1,1,2,False,False,False,True

In [117]:
df.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [118]:
column_names = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason 1', 'Reason 2', 'Reason 3', 'Reason 4']

In [119]:
df.columns = column_names

In [121]:
df.head()

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Reason 1,Reason 2,Reason 3,Reason 4
0,07/07/2015,289,36,33,239.554,30,1,2,1,4,False,False,False,True
1,14/07/2015,118,13,50,239.554,31,1,1,0,0,False,False,False,False
2,15/07/2015,179,51,38,239.554,31,1,0,0,2,False,False,False,True
3,16/07/2015,279,5,39,239.554,24,1,2,0,4,True,False,False,False
4,23/07/2015,289,36,33,239.554,30,1,2,1,2,False,False,False,True

In [122]:
##Concatenate the df_no_age and age_dummies objects you previously obtained. Store the result in a new object called df_concatenated.

df_concatenated = pd.concat([df_no_age, age_dummies],axis=1)
df_concatenated

,Reason for Absence,Date,Transportation Expense,Distance to Work,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,...,39,40,41,43,46,47,48,49,50,58
0,26,07/07/2015,289,36,239.554,30,1,2,1,4,...,False,False,False,False,False,False,False,False,False,False
1,0,14/07/2015,118,13,239.554,31,1,1,0,0,...,False,False,False,False,False,False,False,False,True,False
2,23,15/07/2015,179,51,239.554,31,1,0,0,2,...,False,False,False,False,False,False,False,False,False,False
3,7,16/07/2015,279,5,239.554,24,1,2,0,4,...,True,False,False,False,False,False,False,False,False,False
4,23,23/07/2015,289,36,239.554,30,1,2,1,2,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,10,23/05/2018,179,22,237.656,22,2,2,0,8,...,False,True,False,False,False,False,False,False,False,False
696,6,23/05/2018,225,26,237.656,24,1,1,2,3,...,False,False,False,False,False,False,False,False,False,False
697,10,24/05/2018,330,16,237.656,25,2,0,0,8,...,False,False,False,False,False,False,False,False,False,False
698,23,24/05/2018,235,16,237.656,25,3,0,0,2,...,False,False,False,False,False,False,False,False,False,False
699,28,31/05/2018,291,31,237.656,25,1,1,1,2,...,False,True,False,False,False,False,False,False,False,False

##Reorder Columns

In [123]:
column_names_reordered = ['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4', 'Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']

In [124]:
df = df[column_names_reordered]
df.head()

,Reason 1,Reason 2,Reason 3,Reason 4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,False,False,False,True,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,False,False,False,False,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,False,False,False,True,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,True,False,False,False,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,False,False,False,True,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [125]:
# Reorder the columns from df_concatented in such a way that the ‘Absenteeism Time in Hours’ column appears at the far right of the data set.

df_concatenated.columns.values
column_names = ['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Daily Work Load Average', 'Body Mass Index',
       'Education', 'Children', 'Pets', 27,
       28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39, 40, 41, 43, 46, 47, 48,
       49, 50, 58, 'Absenteeism Time in Hours']
df_concatenated = df_concatenated[column_names]
df_concatenated

,Reason for Absence,Date,Transportation Expense,Distance to Work,Daily Work Load Average,Body Mass Index,Education,Children,Pets,27,...,40,41,43,46,47,48,49,50,58,Absenteeism Time in Hours
0,26,07/07/2015,289,36,239.554,30,1,2,1,False,...,False,False,False,False,False,False,False,False,False,4
1,0,14/07/2015,118,13,239.554,31,1,1,0,False,...,False,False,False,False,False,False,False,True,False,0
2,23,15/07/2015,179,51,239.554,31,1,0,0,False,...,False,False,False,False,False,False,False,False,False,2
3,7,16/07/2015,279,5,239.554,24,1,2,0,False,...,False,False,False,False,False,False,False,False,False,4
4,23,23/07/2015,289,36,239.554,30,1,2,1,False,...,False,False,False,False,False,False,False,False,False,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,10,23/05/2018,179,22,237.656,22,2,2,0,False,...,True,False,False,False,False,False,False,False,False,8
696,6,23/05/2018,225,26,237.656,24,1,1,2,False,...,False,False,False,False,False,False,False,False,False,3
697,10,24/05/2018,330,16,237.656,25,2,0,0,False,...,False,False,False,False,False,False,False,False,False,8
698,23,24/05/2018,235,16,237.656,25,3,0,0,False,...,False,False,False,False,False,False,False,False,False,2
699,28,31/05/2018,291,31,237.656,25,1,1,1,False,...,True,False,False,False,False,False,False,False,False,2

##Creating a Checkpoint

In [195]:
df_reason_mod = df.copy()
df_reason_mod.head()

,Reason 1,Reason 2,Reason 3,Reason 4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,False,False,False,True,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,False,False,False,False,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,False,False,False,True,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,True,False,False,False,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,False,False,False,True,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [196]:
#Create a checkpoint of your work on the exercises, storing the current output in a variable called df_checkpoint.

df_checkpoint = df_concatenated.copy()
df_checkpoint

,Reason for Absence,Date,Transportation Expense,Distance to Work,Daily Work Load Average,Body Mass Index,Education,Children,Pets,27,...,40,41,43,46,47,48,49,50,58,Absenteeism Time in Hours
0,26,07/07/2015,289,36,239.554,30,1,2,1,False,...,False,False,False,False,False,False,False,False,False,4
1,0,14/07/2015,118,13,239.554,31,1,1,0,False,...,False,False,False,False,False,False,False,True,False,0
2,23,15/07/2015,179,51,239.554,31,1,0,0,False,...,False,False,False,False,False,False,False,False,False,2
3,7,16/07/2015,279,5,239.554,24,1,2,0,False,...,False,False,False,False,False,False,False,False,False,4
4,23,23/07/2015,289,36,239.554,30,1,2,1,False,...,False,False,False,False,False,False,False,False,False,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,10,23/05/2018,179,22,237.656,22,2,2,0,False,...,True,False,False,False,False,False,False,False,False,8
696,6,23/05/2018,225,26,237.656,24,1,1,2,False,...,False,False,False,False,False,False,False,False,False,3
697,10,24/05/2018,330,16,237.656,25,2,0,0,False,...,False,False,False,False,False,False,False,False,False,8
698,23,24/05/2018,235,16,237.656,25,3,0,0,False,...,False,False,False,False,False,False,False,False,False,2
699,28,31/05/2018,291,31,237.656,25,1,1,1,False,...,True,False,False,False,False,False,False,False,False,2

##Date Column

In [197]:
df_reason_mod['Date']

0      07/07/2015
1      14/07/2015
2      15/07/2015
3      16/07/2015
4      23/07/2015
          ...
695    23/05/2018
696    23/05/2018
697    24/05/2018
698    24/05/2018
699    31/05/2018
Name: Date, Length: 700, dtype: object

In [198]:
type(df_reason_mod['Date'])

pandas.core.series.Series

In [199]:
type(df_reason_mod['Date'][0])

str

In [200]:
df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'])

ValueError: time data "14/07/2015" doesn't match format "%m/%d/%Y", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [201]:
df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'], format ='%d/%m/%Y')
df_reason_mod['Date']

0     2015-07-07
1     2015-07-14
2     2015-07-15
3     2015-07-16
4     2015-07-23
         ...
695   2018-05-23
696   2018-05-23
697   2018-05-24
698   2018-05-24
699   2018-05-31
Name: Date, Length: 700, dtype: datetime64[ns]

In [202]:
type(df_reason_mod['Date'])

pandas.core.series.Series

##Extracting Month Value

In [203]:
df_reason_mod['Date'][0]

Timestamp('2015-07-07 00:00:00')

In [204]:
#for month value only
df_reason_mod['Date'][0].month

7

In [205]:
list_month = []

In [206]:
#for i in range(700):
#  list_month.append(df_reason_mod['Date'][i].month)

#if no of datas in dataset is not known
for i in range(df_reason_mod.shape[0]):
  list_month.append(df_reason_mod['Date'][i].month)

In [207]:
list_month

[7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5]

In [208]:
len(list_month)

700

In [209]:
df_reason_mod['Month Value']= list_month

In [210]:
df_reason_mod.head()

,Reason 1,Reason 2,Reason 3,Reason 4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month Value
0,False,False,False,True,2015-07-07,289,36,33,239.554,30,1,2,1,4,7
1,False,False,False,False,2015-07-14,118,13,50,239.554,31,1,1,0,0,7
2,False,False,False,True,2015-07-15,179,51,38,239.554,31,1,0,0,2,7
3,True,False,False,False,2015-07-16,279,5,39,239.554,24,1,2,0,4,7
4,False,False,False,True,2015-07-23,289,36,33,239.554,30,1,2,1,2,7

##Extract Day of Week

In [211]:
df_reason_mod['Date'][699].weekday()

3

In [212]:
df_reason_mod['Date'][699]

Timestamp('2018-05-31 00:00:00')

In [213]:
def date_to_weekdays(date_value):
  return date_value.weekday()

In [214]:
df_reason_mod['Days of week']= df_reason_mod['Date'].apply(date_to_weekdays)

In [215]:
df_reason_mod.head()

,Reason 1,Reason 2,Reason 3,Reason 4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month Value,Days of week
0,False,False,False,True,2015-07-07,289,36,33,239.554,30,1,2,1,4,7,1
1,False,False,False,False,2015-07-14,118,13,50,239.554,31,1,1,0,0,7,1
2,False,False,False,True,2015-07-15,179,51,38,239.554,31,1,0,0,2,7,2
3,True,False,False,False,2015-07-16,279,5,39,239.554,24,1,2,0,4,7,3
4,False,False,False,True,2015-07-23,289,36,33,239.554,30,1,2,1,2,7,3

In [216]:
df_reason_mod.columns.values

array(['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4', 'Date',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Month Value',
       'Days of week'], dtype=object)

In [219]:
df_reason_mod = df_reason_mod.drop(['Date'], axis = 1)
column_names_upd = ['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4', 'Month Value', 'Days of week',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
       'Pets', 'Absenteeism Time in Hours']
df_reason_mod = df_reason_mod[column_names_upd]

In [220]:
# Create a Checkpoint
df_reason_date_mod = df_reason_mod.copy()
df_reason_date_mod

,Reason 1,Reason 2,Reason 3,Reason 4,Month Value,Days of week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,False,False,False,True,7,1,289,36,33,239.554,30,1,2,1,4
1,False,False,False,False,7,1,118,13,50,239.554,31,1,1,0,0
2,False,False,False,True,7,2,179,51,38,239.554,31,1,0,0,2
3,True,False,False,False,7,3,279,5,39,239.554,24,1,2,0,4
4,False,False,False,True,7,3,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,True,False,False,False,5,2,179,22,40,237.656,22,2,2,0,8
696,True,False,False,False,5,2,225,26,28,237.656,24,1,1,2,3
697,True,False,False,False,5,3,330,16,28,237.656,25,2,0,0,8
698,False,False,False,True,5,3,235,16,32,237.656,25,3,0,0,2
699,False,False,False,True,5,3,291,31,40,237.656,25,1,1,1,2

In [221]:
type(df_reason_date_mod['Transportation Expense'][0])

numpy.int64

In [223]:
type(df_reason_date_mod['Distance to Work'][0])

numpy.int64

In [224]:
type(df_reason_date_mod['Age'][0])

numpy.int64

In [228]:
type(df_reason_date_mod['Daily Work Load Average'][0])

numpy.float64

In [229]:
type(df_reason_date_mod['Body Mass Index'][0])

numpy.int64

## Education, Children, Pets

In [230]:
df_reason_date_mod['Education'].unique()

array([1, 3, 2, 4])

In [231]:
df_reason_date_mod['Education'].value_counts()

Education
1    583
3     73
2     40
4      4
Name: count, dtype: int64

In [232]:
df_reason_date_mod['Education'] = df_reason_date_mod['Education'].map({1:0,2:1,3:1,4:1})

In [233]:
df_reason_date_mod['Education'].unique()

array([0, 1])

In [234]:
df_reason_date_mod['Education'].value_counts()

Education
0    583
1    117
Name: count, dtype: int64

##Final Checkpoint

In [235]:
df_preprocessed = df_reason_date_mod.copy()
df_preprocessed.head()

,Reason 1,Reason 2,Reason 3,Reason 4,Month Value,Days of week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,False,False,False,True,7,1,289,36,33,239.554,30,0,2,1,4
1,False,False,False,False,7,1,118,13,50,239.554,31,0,1,0,0
2,False,False,False,True,7,2,179,51,38,239.554,31,0,0,0,2
3,True,False,False,False,7,3,279,5,39,239.554,24,0,2,0,4
4,False,False,False,True,7,3,289,36,33,239.554,30,0,2,1,2

In [236]:
df_preprocessed.to_csv('Absenteeism_preprocessed.csv', index=False)